name: Deploy to GitHub Pages
on:
  push:
    branches:
      - master # Adjust to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4

      - name: Install Composer dependencies
        run: composer install

      - name: Build and deploy
        run: |
          mkdir -p docs
          php index.php > docs/index.html
          cp -r application/assets docs/application/
          cp -r templates docs/
        env:
          COMPOSER_PROCESS_TIMEOUT: 0
          COMPOSER_NO_INTERACTION: 1
          COMPOSER_NO_AUDIT: 1

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.WORKFLOW_TOKEN }}
          publish_dir: ./docs
